feat: support to filter by ObjectId
LesliTech/lesli-nodejs-mongodb-tools pull request #8
Opened 2022-06-02 06:11 UTC by mbonii

2022-06-02 16:01 UTC, FR98 approved these changes

2022-06-03 07:29 UTC, ldonis requested changes

2022-06-03 07:29 UTC, ldonis commented on src/query/database-collection-document.js
> +            if(query.match && query.match._id){
aqui se podria hacer algo como query?.match?._id y ya que estamos revisando si existe el id podriamos dejarlo mas simple, que query acepte "id" en lugar de "_id" :)

2022-06-03 13:23 UTC, mbonii commented on src/query/database-collection-document.js
> +            if(query.match && query.match._id){
un metodo como `?` no existe, pero si podriamos cambiar `id` a  `_id` para que sea mas amigable para el dev

2022-06-03 14:44 UTC, mbonii commented on src/query/database-collection-document.js
> +            if(query.match && query.match._id){
listo :)

2022-06-07 07:44 UTC, ldonis approved these changes

2022-06-07 07:45 UTC, merged